import { useEffect, useState } from "react";
import type { DailyRecord, DailyRecordInput, DayType } from "../api";
import { hours, minuteToTime, timeToMinute } from "../api";
import { messages as m } from "../constants/messages";
import { Button, Card, Field } from "../components/ui";

export const DailyEntryView = ({ record, dates, selectedDate, onDate, onSave, onClear }: { record: Omit<DailyRecord, "id"> | DailyRecord; dates: string[]; selectedDate: string; onDate: (date: string) => void; onSave: (record: DailyRecordInput) => void; onClear: () => void }) => {
  const [form, setForm] = useState(() => ({ ...record, tasksText: record.tasks.map((task) => task.text).join("\n") }));
  const [override, setOverride] = useState<Record<string, number>>({ regularMinutes: record.regularMinutes, nightDiffMinutes: record.nightDiffMinutes, regularOtMinutes: record.regularOtMinutes, nightDiffOtMinutes: record.nightDiffOtMinutes, restDayMinutes: record.restDayMinutes, restDayOtMinutes: record.restDayOtMinutes, holidayMinutes: record.holidayMinutes });
  useEffect(() => {
    setForm({ ...record, tasksText: record.tasks.map((task) => task.text).join("\n") });
    setOverride({ regularMinutes: record.regularMinutes, nightDiffMinutes: record.nightDiffMinutes, regularOtMinutes: record.regularOtMinutes, nightDiffOtMinutes: record.nightDiffOtMinutes, restDayMinutes: record.restDayMinutes, restDayOtMinutes: record.restDayOtMinutes, holidayMinutes: record.holidayMinutes });
  }, [record.workDate]);
  const set = (key: string, value: unknown) => setForm((current) => ({ ...current, [key]: value }));
  const summary = [{ label: m.regularHours, value: form.regularMinutes }, { label: m.nightOtHours, value: form.nightDiffOtMinutes }, { label: m.overtimeHours, value: form.regularOtMinutes }, { label: m.restDayHours, value: form.restDayMinutes + form.restDayOtMinutes }];
  const overrideFields = [{ key: "regularMinutes", label: m.regularHours }, { key: "nightDiffMinutes", label: m.nightOtHours }, { key: "regularOtMinutes", label: m.overtimeHours }, { key: "nightDiffOtMinutes", label: m.nightOtHours }, { key: "restDayMinutes", label: m.restDayHours }, { key: "restDayOtMinutes", label: m.overtimeHours }, { key: "holidayMinutes", label: m.holiday }];
  return <div className="stack">
    <div className="section-heading"><div><p className="eyebrow">{m.dailyEntry}</p><h2>{selectedDate}</h2></div><select value={selectedDate} onChange={(event) => onDate(event.target.value)}>{dates.map((date) => <option key={date}>{date}</option>)}</select></div>
    <Card title={m.attendance}><div className="form-grid">
      <Field label={m.dayType}><select value={form.dayType} onChange={(event) => { const dayType = event.target.value as DayType; set("dayType", dayType); set("breakMinutes", dayType === "WORKDAY" ? 60 : 0); }}>{["WORKDAY", "REST_DAY", "HOLIDAY", "LEAVE", "ABSENT"].map((type) => <option key={type} value={type}>{type === "WORKDAY" ? m.workday : type === "REST_DAY" ? m.restDay : type === "HOLIDAY" ? m.holiday : type === "LEAVE" ? m.leaveDay : m.absent}</option>)}</select></Field>
      <Field label={m.timeIn}><input type="time" value={minuteToTime(form.clockInMinute)} onChange={(event) => set("clockInMinute", timeToMinute(event.target.value))} /></Field>
      <Field label={m.timeOut}><input type="time" value={minuteToTime(form.clockOutMinute)} onChange={(event) => set("clockOutMinute", timeToMinute(event.target.value))} /></Field>
      <Field label={m.breakMinutes}><input type="number" min="0" max="720" value={form.breakMinutes} onChange={(event) => set("breakMinutes", Number(event.target.value))} /></Field>
      <Field label={m.calculation}><select value={form.calculationMode} onChange={(event) => set("calculationMode", event.target.value)}><option value="AUTO">{m.automatic}</option><option value="OVERRIDE">{m.override}</option></select></Field>
    </div><label className="checkbox"><input type="checkbox" checked={form.endsNextDay} onChange={(event) => set("endsNextDay", event.target.checked)} />{m.overnight}</label>{form.calculationMode === "OVERRIDE" && <div className="form-grid override-grid">{overrideFields.map((item) => <Field key={item.key} label={item.label}><input type="number" min="0" step="0.25" value={(override[item.key] || 0) / 60} onChange={(event) => setOverride({ ...override, [item.key]: Math.round(Number(event.target.value) * 60) })} /></Field>)}</div>}</Card>
    <Card title={m.tasks}><div className="form-grid"><Field label={m.activity}><input value={form.activity} onChange={(event) => set("activity", event.target.value)} /></Field><Field label={m.type}><input value={form.accomplishmentType} onChange={(event) => set("accomplishmentType", event.target.value)} /></Field><Field label={m.status}><input value={form.accomplishmentStatus} onChange={(event) => set("accomplishmentStatus", event.target.value)} /></Field><Field label={m.hoursSpent}><input type="number" min="0" step="0.25" value={form.hoursSpentMinutes / 60} onChange={(event) => set("hoursSpentMinutes", Math.round(Number(event.target.value) * 60))} /></Field></div><Field label={m.taskHint}><textarea rows={8} value={form.tasksText} onChange={(event) => set("tasksText", event.target.value)} /></Field><Field label={m.remarks}><textarea rows={3} value={form.remarks} onChange={(event) => set("remarks", event.target.value)} /></Field></Card>
    <Card title={m.review}><div className="summary-grid">{summary.map((item) => <div key={item.label}><span>{item.label}</span><strong>{hours(item.value)}</strong></div>)}</div><div className="inline-actions"><Button onClick={() => onSave({ dayType: form.dayType, clockInMinute: form.clockInMinute, clockOutMinute: form.clockOutMinute, endsNextDay: form.endsNextDay, breakMinutes: form.breakMinutes, calculationMode: form.calculationMode, override: form.calculationMode === "OVERRIDE" ? override : undefined, activity: form.activity, accomplishmentType: form.accomplishmentType, accomplishmentStatus: form.accomplishmentStatus, hoursSpentMinutes: form.hoursSpentMinutes, remarks: form.remarks, tasks: form.tasksText.split("\n").map((task) => task.trim()).filter(Boolean) })}>{m.save}</Button><Button secondary onClick={onClear}>{m.delete}</Button></div></Card>
  </div>;
};
