import { useEffect, useState } from "react";
import type { DailyRecord, DailyRecordInput, DayType } from "../api";
import { hours, minuteToTime, timeToMinute } from "../api";
import { messages as m } from "../constants/messages";
import { Button, Card, Field } from "../components/ui";

export const DailyEntryView = ({ record, dates, selectedDate, onDate, onSave, onClear, saving, clearing }: { record: Omit<DailyRecord, "id"> | DailyRecord; dates: string[]; selectedDate: string; onDate: (date: string) => void; onSave: (record: DailyRecordInput) => void; onClear: () => void; saving: boolean; clearing: boolean }) => {
  const [form, setForm] = useState(() => ({ ...record, tasksText: record.tasks.map((task) => task.text).join("\n") }));
  const [override, setOverride] = useState<Record<string, number>>({ regularMinutes: record.regularMinutes, nightDiffMinutes: record.nightDiffMinutes, regularOtMinutes: record.regularOtMinutes, nightDiffOtMinutes: record.nightDiffOtMinutes, restDayMinutes: record.restDayMinutes, restDayOtMinutes: record.restDayOtMinutes, holidayMinutes: record.holidayMinutes });
  useEffect(() => {
    setForm({ ...record, tasksText: record.tasks.map((task) => task.text).join("\n") });
    setOverride({ regularMinutes: record.regularMinutes, nightDiffMinutes: record.nightDiffMinutes, regularOtMinutes: record.regularOtMinutes, nightDiffOtMinutes: record.nightDiffOtMinutes, restDayMinutes: record.restDayMinutes, restDayOtMinutes: record.restDayOtMinutes, holidayMinutes: record.holidayMinutes });
  }, [record.workDate]);
  const set = (key: string, value: unknown) => setForm((current) => ({ ...current, [key]: value }));
  const summary = [{ label: m.regularHours, value: form.regularMinutes }, { label: m.nightOtHours, value: form.nightDiffOtMinutes }, { label: m.overtimeHours, value: form.regularOtMinutes }, { label: m.restDayHours, value: form.restDayMinutes + form.restDayOtMinutes }];
  const overrideFields = [{ key: "regularMinutes", label: m.regularHours }, { key: "nightDiffMinutes", label: m.nightOtHours }, { key: "regularOtMinutes", label: m.overtimeHours }, { key: "nightDiffOtMinutes", label: m.nightOtHours }, { key: "restDayMinutes", label: m.restDayHours }, { key: "restDayOtMinutes", label: m.overtimeHours }, { key: "holidayMinutes", label: m.holiday }];
  return <div className="grid gap-5">
    <div className="flex items-end justify-between gap-4"><div><p className="mb-0 text-[11px] font-bold uppercase tracking-[.08em] text-[#6684ad]">{m.dailyEntry}</p><h2 className="mt-1 text-[23px] font-bold tracking-[-.03em] text-ink">{selectedDate}</h2></div><select className="w-full max-w-[220px] rounded-lg border border-slate-200 bg-white px-2.5 py-2.5 text-ink outline-none focus:border-brand focus:ring-4 focus:ring-brand/10" value={selectedDate} onChange={(event) => onDate(event.target.value)}>{dates.map((date) => <option key={date}>{date}</option>)}</select></div>
    <Card title={m.attendance}><div className="grid grid-cols-2 gap-[15px] max-[800px]:grid-cols-1">
      <Field label={m.dayType}><select value={form.dayType} onChange={(event) => { const dayType = event.target.value as DayType; set("dayType", dayType); set("breakMinutes", dayType === "WORKDAY" ? 60 : 0); }}>{["WORKDAY", "REST_DAY", "HOLIDAY", "LEAVE", "ABSENT"].map((type) => <option key={type} value={type}>{type === "WORKDAY" ? m.workday : type === "REST_DAY" ? m.restDay : type === "HOLIDAY" ? m.holiday : type === "LEAVE" ? m.leaveDay : m.absent}</option>)}</select></Field>
      <Field label={m.timeIn}><input type="time" value={minuteToTime(form.clockInMinute)} onChange={(event) => set("clockInMinute", timeToMinute(event.target.value))} /></Field>
      <Field label={m.timeOut}><input type="time" value={minuteToTime(form.clockOutMinute)} onChange={(event) => set("clockOutMinute", timeToMinute(event.target.value))} /></Field>
      <Field label={m.breakMinutes}><input type="number" min="0" max="720" value={form.breakMinutes} onChange={(event) => set("breakMinutes", Number(event.target.value))} /></Field>
      <Field label={m.calculation}><select value={form.calculationMode} onChange={(event) => set("calculationMode", event.target.value)}><option value="AUTO">{m.automatic}</option><option value="OVERRIDE">{m.override}</option></select></Field>
    </div><label className="mt-[17px] flex items-center gap-2 text-[13px] text-slate-600"><input className="accent-brand" type="checkbox" checked={form.endsNextDay} onChange={(event) => set("endsNextDay", event.target.checked)} />{m.overnight}</label>{form.calculationMode === "OVERRIDE" && <div className="mt-4 grid grid-cols-2 gap-[15px] max-[800px]:grid-cols-1">{overrideFields.map((item) => <Field key={item.key} label={item.label}><input type="number" min="0" step="0.25" value={(override[item.key] || 0) / 60} onChange={(event) => setOverride({ ...override, [item.key]: Math.round(Number(event.target.value) * 60) })} /></Field>)}</div>}</Card>
    <Card title={m.tasks}><div className="grid grid-cols-2 gap-[15px] max-[800px]:grid-cols-1"><Field label={m.activity}><input value={form.activity} onChange={(event) => set("activity", event.target.value)} /></Field><Field label={m.type}><input value={form.accomplishmentType} onChange={(event) => set("accomplishmentType", event.target.value)} /></Field><Field label={m.status}><input value={form.accomplishmentStatus} onChange={(event) => set("accomplishmentStatus", event.target.value)} /></Field><Field label={m.hoursSpent}><input type="number" min="0" step="0.25" value={form.hoursSpentMinutes / 60} onChange={(event) => set("hoursSpentMinutes", Math.round(Number(event.target.value) * 60))} /></Field></div><Field label={m.taskHint}><textarea rows={8} value={form.tasksText} onChange={(event) => set("tasksText", event.target.value)} /></Field><Field label={m.remarks}><textarea rows={3} value={form.remarks} onChange={(event) => set("remarks", event.target.value)} /></Field></Card>
    <Card title={m.review}><div className="grid grid-cols-4 gap-[11px] max-[800px]:grid-cols-2">{summary.map((item) => <div className="rounded-lg bg-slate-50 p-[13px]" key={item.label}><span className="block text-[11px] text-slate-500">{item.label}</span><strong className="mt-1 block text-[19px] text-ink">{hours(item.value)}</strong></div>)}</div><div className="mt-[18px] flex gap-2"><Button disabled={saving} onClick={() => onSave({ dayType: form.dayType, clockInMinute: form.clockInMinute, clockOutMinute: form.clockOutMinute, endsNextDay: form.endsNextDay, breakMinutes: form.breakMinutes, calculationMode: form.calculationMode, override: form.calculationMode === "OVERRIDE" ? override : undefined, activity: form.activity, accomplishmentType: form.accomplishmentType, accomplishmentStatus: form.accomplishmentStatus, hoursSpentMinutes: form.hoursSpentMinutes, remarks: form.remarks, tasks: form.tasksText.split("\n").map((task) => task.trim()).filter(Boolean) })}>{m.save}</Button><Button disabled={clearing} secondary onClick={onClear}>{m.delete}</Button></div></Card>
  </div>;
};
