import { useState } from "react";
import type { Profile } from "../api";
import { minuteToTime, timeToMinute } from "../api";
import { messages as m } from "../constants/messages";
import { Button, Card, Field } from "../components/ui";

export const SettingsView = ({ profile, onSave, saving }: { profile: Profile; onSave: (profile: Profile) => Promise<Profile | null>; saving: boolean }) => {
  const [draft, setDraft] = useState(profile);
  const set = (key: keyof Profile, value: string | number) => setDraft((current) => ({ ...current, [key]: value }));
  const save = async () => { const saved = await onSave(draft); if (saved) setDraft(saved); };
  return <div className="grid gap-5"><div className="flex items-end justify-between gap-4"><div><p className="mb-0 text-[11px] font-bold uppercase tracking-[.08em] text-[#6684ad]">{m.settings}</p><h2 className="mt-1 text-[23px] font-bold tracking-[-.03em] text-ink">{m.profile}</h2></div></div><Card title={m.profile}><div className="grid grid-cols-2 gap-[15px] max-[800px]:grid-cols-1"><Field label={m.employeeName}><input value={draft.employeeName} onChange={(event) => set("employeeName", event.target.value)} /></Field><Field label={m.employeeId}><input value={draft.employeeId} onChange={(event) => set("employeeId", event.target.value)} /></Field><Field label={m.position}><input value={draft.position} onChange={(event) => set("position", event.target.value)} /></Field><Field label={m.projectAssignment}><input value={draft.projectAssignment} onChange={(event) => set("projectAssignment", event.target.value)} /></Field><Field label={m.validatorName}><input value={draft.validatorName} onChange={(event) => set("validatorName", event.target.value)} /></Field><Field label={m.supervisorName}><input value={draft.supervisorName} onChange={(event) => set("supervisorName", event.target.value)} /></Field></div></Card><Card title={m.payrollRules}><div className="grid grid-cols-2 gap-[15px] max-[800px]:grid-cols-1"><Field label={m.shiftStart}><input type="time" value={minuteToTime(draft.shiftStartMinute)} onChange={(event) => set("shiftStartMinute", timeToMinute(event.target.value) || 0)} /></Field><Field label={m.shiftEnd}><input type="time" value={minuteToTime(draft.shiftEndMinute)} onChange={(event) => set("shiftEndMinute", timeToMinute(event.target.value) || 0)} /></Field><Field label={m.standardBreak}><input type="number" value={draft.standardBreakMinutes} onChange={(event) => set("standardBreakMinutes", Number(event.target.value))} /></Field><Field label={m.regularLimit}><input type="number" value={draft.regularLimitMinutes / 60} step="0.25" onChange={(event) => set("regularLimitMinutes", Math.round(Number(event.target.value) * 60))} /></Field><Field label={m.nightStart}><input type="time" value={minuteToTime(draft.nightStartMinute)} onChange={(event) => set("nightStartMinute", timeToMinute(event.target.value) || 0)} /></Field><Field label={m.nightEnd}><input type="time" value={minuteToTime(draft.nightEndMinute)} onChange={(event) => set("nightEndMinute", timeToMinute(event.target.value) || 0)} /></Field></div><Button disabled={saving} onClick={() => void save()}>{m.save}</Button></Card></div>;
};
