import type { Profile } from "../api";
import { minuteToTime, timeToMinute } from "../api";
import { messages as m } from "../constants/messages";
import { Button, Card, Field } from "../components/ui";

export const SettingsView = ({ profile, setProfile, onSave }: { profile: Profile; setProfile: (profile: Profile) => void; onSave: () => void }) => {
  const set = (key: keyof Profile, value: string | number) => setProfile({ ...profile, [key]: value });
  return <div className="stack"><div className="section-heading"><div><p className="eyebrow">{m.settings}</p><h2>{m.profile}</h2></div></div><Card title={m.profile}><div className="form-grid"><Field label={m.employeeName}><input value={profile.employeeName} onChange={(event) => set("employeeName", event.target.value)} /></Field><Field label={m.employeeId}><input value={profile.employeeId} onChange={(event) => set("employeeId", event.target.value)} /></Field><Field label={m.position}><input value={profile.position} onChange={(event) => set("position", event.target.value)} /></Field><Field label={m.projectAssignment}><input value={profile.projectAssignment} onChange={(event) => set("projectAssignment", event.target.value)} /></Field><Field label={m.validatorName}><input value={profile.validatorName} onChange={(event) => set("validatorName", event.target.value)} /></Field><Field label={m.supervisorName}><input value={profile.supervisorName} onChange={(event) => set("supervisorName", event.target.value)} /></Field></div></Card><Card title={m.payrollRules}><div className="form-grid"><Field label={m.shiftStart}><input type="time" value={minuteToTime(profile.shiftStartMinute)} onChange={(event) => set("shiftStartMinute", timeToMinute(event.target.value) || 0)} /></Field><Field label={m.shiftEnd}><input type="time" value={minuteToTime(profile.shiftEndMinute)} onChange={(event) => set("shiftEndMinute", timeToMinute(event.target.value) || 0)} /></Field><Field label={m.standardBreak}><input type="number" value={profile.standardBreakMinutes} onChange={(event) => set("standardBreakMinutes", Number(event.target.value))} /></Field><Field label={m.regularLimit}><input type="number" value={profile.regularLimitMinutes / 60} step="0.25" onChange={(event) => set("regularLimitMinutes", Math.round(Number(event.target.value) * 60))} /></Field><Field label={m.nightStart}><input type="time" value={minuteToTime(profile.nightStartMinute)} onChange={(event) => set("nightStartMinute", timeToMinute(event.target.value) || 0)} /></Field><Field label={m.nightEnd}><input type="time" value={minuteToTime(profile.nightEndMinute)} onChange={(event) => set("nightEndMinute", timeToMinute(event.target.value) || 0)} /></Field></div><Button onClick={onSave}>{m.save}</Button></Card></div>;
};
