import type { ButtonHTMLAttributes, ReactNode } from "react";

const fieldClass = "grid gap-2 text-xs font-semibold text-slate-600 [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-slate-200 [&_input]:bg-white [&_input]:px-2.5 [&_input]:py-2.5 [&_input]:text-ink [&_input]:outline-none [&_input:focus]:border-brand [&_input:focus]:ring-4 [&_input:focus]:ring-brand/10 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:border-slate-200 [&_select]:bg-white [&_select]:px-2.5 [&_select]:py-2.5 [&_select]:text-ink [&_select]:outline-none [&_select:focus]:border-brand [&_select:focus]:ring-4 [&_select:focus]:ring-brand/10 [&_textarea]:w-full [&_textarea]:resize-y [&_textarea]:rounded-lg [&_textarea]:border [&_textarea]:border-slate-200 [&_textarea]:bg-white [&_textarea]:px-2.5 [&_textarea]:py-2.5 [&_textarea]:leading-relaxed [&_textarea]:text-ink [&_textarea]:outline-none [&_textarea:focus]:border-brand [&_textarea:focus]:ring-4 [&_textarea:focus]:ring-brand/10";
export const Field = ({ label, children }: { label: string; children: ReactNode }) => <label className={fieldClass}><span>{label}</span>{children}</label>;

const buttonBase = "inline-flex items-center justify-center rounded-lg px-[15px] py-2.5 text-[13px] font-bold transition-colors focus:outline-none focus:ring-4 focus:ring-brand/15 disabled:cursor-wait disabled:opacity-70";
export const Button = ({ children, secondary = false, className = "", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { secondary?: boolean }) => <button className={`${buttonBase} ${secondary ? "bg-slate-100 text-slate-600 shadow-none hover:bg-slate-200" : "bg-brand text-white shadow-[0_4px_10px_rgb(51_120_232/17%)] hover:bg-brand-dark"} ${className}`} {...props}>{children}</button>;

export const Card = ({ title, children, action }: { title?: string; children: ReactNode; action?: ReactNode }) => <section className="rounded-[14px] border border-border bg-white p-[21px] shadow-[0_8px_28px_rgb(32_53_93/3%)]">{title && <div className="mb-4 flex items-start justify-between gap-[18px]"><h2 className="m-0 text-base">{title}</h2>{action}</div>}{children}</section>;
